name: CellVision CI

on:
  push:
    branches:
      - develop
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Login to Docker Hub
      run: echo ${{ secrets.DOCKERHUB_ACCESS_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

    - name: Determine artifact name
      run: |
        if [[ $GITHUB_REF == refs/heads/develop ]]; then
          ARTIFACT_NAME=${{ secrets.DOCKERHUB_USERNAME }}/cellvision:latest-SNAPSHOT
        elif [[ $GITHUB_REF == refs/heads/master ]]; then
          ARTIFACT_NAME=${{ secrets.DOCKERHUB_USERNAME }}/cellvision:latest
        fi
        echo "::set-env name=ARTIFACT_NAME::$ARTIFACT_NAME"

    - name: Build and push Docker image
      run: |
        docker buildx create --use
        docker buildx build \
          --file Dockerfile \
          --tag $ARTIFACT_NAME \
          --push .

    env:
      DOCKER_CLI_EXPERIMENTAL: enabled
      DOCKER_BUILDKIT: 1
